# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - name: Checkout Code 
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install py2app
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build 
        run: |
            python setup.py py2app
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: $GITHUB_RUN_ID
          release_name: $GITHUB_RUN_ID
          draft: false
          prerelease: false
      - name: Attatch Binary
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/202020.app
          asset_name: 202020app 
          tag: $GITHUB_RUN_ID
          overwrite: true
            
            
        
